name: Build code, run unit test, run SAST, SCA, DAST security scans
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
#        projectBaseDir: my-custom-directory
        args: >
          -Dsonar.organization=dotnetgithubactionsorg
          -Dsonar.projectKey=dotnetgithubactionsproject
#             -Dsonar.python.coverage.reportPaths=coverage.xml
#             -Dsonar.sources=
#             -Dsonar.test.exclusions=
#             -Dsonar.tests=
#             -Dsonar.verbose=true
 
