name: Build code, run unit test, run SAST, SCA, DAST security scans
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          #projectBaseDir: my-custom-directory
          args: >
            -Dsonar.organization=javaprojectreachability
            -Dsonar.projectKey=javaprojectreachability
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=views
            -Dsonar.test.exclusions=
            -Dsonar.tests=
            -Dsonar.verbose=true
 
